export const englishQuotes = [
  "Believe in yourself and all that you are.",
  "Do one thing every day that scares you.",
  "Success is not in what you have, but who you are.",
  "Dream big and dare to fail.",
  "Don’t wait. The time will never be just right.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Push yourself, because no one else is going to do it for you.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Sometimes later becomes never. Do it now.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "It's going to be hard, but hard does not mean impossible.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Discipline is the bridge between goals and accomplishment.",
  "Your only limit is your mind.",
  "Act as if what you do makes a difference. It does.",
  "Dream it. Wish it. Do it.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Try to be a rainbow in someone else's cloud.",
  "Make each day your masterpiece.",
  "Nothing will work unless you do.",
  "Every moment is a fresh beginning.",
  "Never regret anything that made you smile.",
  "Die with memories, not dreams.",
  "Aspire to inspire before we expire.",
  "Be the reason someone smiles today.",
  "The best time for new beginnings is now.",
  "You are capable of amazing things.",
  "Difficult roads often lead to beautiful destinations.",
  "Start where you are. Use what you have. Do what you can.",
  "Don’t let yesterday take up too much of today.",
  "You don’t have to be perfect to be amazing.",
  "Life is short. Smile while you still have teeth.",
  "Sometimes you win, sometimes you learn.",
  "Your vibe attracts your tribe.",
  "Stay hungry, stay foolish.",
  "You can if you think you can.",
  "There is no traffic jam on the extra mile.",
  "Turn your wounds into wisdom.",
  "You become what you believe.",
  "Take the risk or lose the chance.",
  "Work hard in silence. Let success make the noise.",
  "Progress, not perfection.",
  "Be so good they can’t ignore you.",
  "In a world where you can be anything, be kind.",
  "You are stronger than you think.",
  "You were born to be real, not perfect.",
  "Do what is right, not what is easy.",
  "Patience is also a form of action.",
  "A comfort zone is a beautiful place, but nothing ever grows there.",
  "Be stubborn about your goals, but flexible about your methods.",
  "Success isn’t owned. It’s leased. And rent is due every day.",
  "Effort only fully releases its reward after a person refuses to quit.",
  "You didn’t come this far to only come this far.",
  "Work for a cause, not for applause.",
  "Live your life, not someone else's version of it.",
  "Typing fast requires a lot of practice and accuracy.",
  "Improving typing speed requires consistency and patience.",
  "Learning to type is a valuable skill in today’s digital world.",
  "When typing, always focus on accuracy before speed.",
  "Fast typing comes naturally after consistent practice over time.",
  "Keep your eyes on the screen, not the keyboard.",
  "Proper hand placement is essential for efficient typing.",
  "Speed without accuracy leads to frustration and poor results.",
  "Set small goals and reward yourself as you improve.",
  "Typing is not just about speed — it’s about control.",
  "You can always get faster, but you must stay accurate.",
  "Never underestimate the power of a good warm-up session.",
  "Confidence grows when you push through discomfort.",
  "Remember, every expert was once a beginner.",
  "The journey to mastery starts with your first keystroke.",
  "Don’t rush. Type with intention and care.",
  "Focus on flow, not just the finish line.",
  "Enjoy the rhythm of your fingers dancing on the keyboard.",
  "Let the words flow from your mind through your fingers.",
  "Typing is like music — rhythm matters.",
  "Typing is a modern form of craftsmanship. Each keystroke contributes to the creation of something larger: a message, an idea, a piece of knowledge. Whether you’re writing a quick email or a full-length article, your ability to type fluently affects how effectively you communicate with the world. Take pride in practicing. Take pride in your speed, your accuracy, and the confidence that comes with every letter you type.",
  "There is no shortcut to typing mastery. It takes time, focus, and thousands of keystrokes. But each time you show up and give it your best, you’re getting closer. Closer to fluency, to comfort, to effortless communication. Let your keyboard be your canvas, and your fingers the brushes. Paint your thoughts clearly, confidently, and fast.",
  "Here is a longer passage to challenge your typing endurance. Typing fast is a skill that combines memory, muscle control, and mental clarity. When you sit down to practice, remove distractions and focus entirely on the words. You’ll notice how your mind and fingers begin to work in harmony. Each session builds upon the last — improving not just your speed, but also your confidence and accuracy.",
  "The process of learning to type can feel slow at first, but progress comes with time. It's not just about hitting the right keys — it's about understanding the structure of language, anticipating the next letter, and feeling the rhythm of your own thoughts flowing through your fingers. As you get better, you'll feel more connected to the words on the screen, like they are an extension of your own ideas. That's when typing becomes not just a skill, but a superpower.",
  "Long texts like this one give you an opportunity to improve endurance. It's easy to type short bursts of words, but maintaining focus over longer paragraphs builds real skill. Keep your breathing steady, your posture straight, and your eyes fixed on your goal. Don’t panic over typos — correct them quickly and move on. The more relaxed you are, the more natural your typing becomes.",
  "Be willing to be a beginner every single morning.",
  "Action is the foundational key to all success.",
  "Don’t count the days, make the days count.",
  "You only live once, but if you do it right, once is enough.",
  "Go the extra mile. It’s never crowded.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Try not to become a person of success, but rather a person of value.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The secret of getting ahead is getting started.",
  "If you want to lift yourself up, lift up someone else.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "You miss 100% of the shots you don’t take.",
  "Be the change that you wish to see in the world.",
  "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
  "Do what you can, with what you have, where you are.",
  "You are never too old to set another goal or to dream a new dream.",
  "The best way to predict the future is to create it.",
  "He who has a why to live can bear almost any how.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Every keystroke brings you closer to mastery.",
  "Mistakes are proof that you are trying.",
  "Typing fast is a journey, not a race.",
  "Focus fuels progress; distraction stalls it.",
  "Success is built on a foundation of daily habits.",
  "Let your fingers tell the story of your mind.",
  "Confidence grows with each practice session.",
  "The keyboard is your tool; practice is your craftsman.",
  "Small improvements lead to big breakthroughs.",
  "Don’t just type—communicate with clarity and purpose.",
  "Patience and persistence turn typing into an art.",
  "When you feel stuck, slow down to speed up.",
  "Greatness is forged by embracing challenges.",
  "Practice with intention, and speed will follow.",
  "Typing well is more than speed; it’s about control.",
  "Dream big, type fast, stay accurate.",
  "Your mind leads, your fingers follow.",
  "Discipline is the silent architect of success.",
  "The best way to improve is to never stop trying.",
  "The rhythm of your typing is the rhythm of your focus.",
  "Every word typed is progress toward your goal.",
  "Believe in the power of your practice.",
  "Accuracy is the seed; speed is the fruit.",
  "Success comes to those who refuse to quit.",
  "Let every session be a step forward.",
  "The difference between good and great is just a little more effort.",
  "Typing quickly is a skill; typing well is a mindset.",
  "Practice doesn’t make perfect—perfect practice makes perfect.",
  "Push past the frustration and keep your eyes on the prize.",
  "In typing, as in life, consistency beats bursts.",
  "Learn to love the process, not just the result.",
  "Your speed will increase as your confidence grows.",
  "Mistakes are the stepping stones to mastery.",
  "Every hour of practice compounds your skill.",
  "Slow and steady builds unshakable foundations.",
  "Typing is a superpower in a digital world.",
  "Accuracy first, speed will follow naturally.",
  "Celebrate your progress, no matter how small.",
  "Your fingers hold the power to create worlds.",
  "Typing well saves time, frustration, and effort.",
  "Stay consistent and watch your skills soar.",
  "Success is forged by thousands of keystrokes.",
  "Your focus is your greatest typing ally.",
  "Patience transforms effort into excellence.",
  "Practice until your fingers forget the struggle.",
  "Typing fluency comes from daily commitment.",
  "You are a typist, an artist, a communicator.",
  "Never stop practicing, never stop improving.",
  "The keyboard is a playground for your thoughts.",
  "Typing speed is a byproduct of passion and practice.",
  "The joy of typing is found in flow, not speed.",
  "Your journey to typing mastery starts today.",
  "Mistakes are just milestones on the road to success.",
  "Each session is an opportunity to grow.",
  "Typing builds bridges between ideas and reality.",
  "Hard work in practice brings ease in performance.",
  "Typing is a skill, but it’s also a discipline.",
  "Dedication turns effort into achievement.",
  "Speed is important, but precision is power.",
  "Let your fingers dance across the keys with confidence.",
  "Typing transforms thoughts into action.",
  "Commitment fuels progress in typing and life.",
  "Mastery comes to those who never quit.",
  "Celebrate every word, every sentence, every page.",
  "Typing fast is impressive, typing well is invaluable.",
  "Every keystroke is a victory over yesterday’s limits.",
  "Let focus and patience guide your practice.",
  "Your fingers tell the story of your dedication.",
  "Typing is not a race, but a craft to perfect.",
  "Train your fingers to follow your mind’s voice.",
  "Perseverance transforms effort into skill.",
  "Typing mastery opens doors to countless opportunities.",
  "Consistency is your most valuable typing tool.",
  "Enjoy the process as much as the progress.",
  "Each practice session plants seeds for growth.",
  "Great typists were once beginners just like you.",
  "Keep your eyes on the screen and your mind in the moment.",
  "Don’t fear mistakes; they are proof of your growth.",
  "Your typing speed will surprise you with patience.",
  "Every letter typed brings you closer to fluency.",
  "Stay humble, keep practicing, achieve greatness.",
  "Your keyboard is a gateway to your creativity.",
  "Typing well is the foundation for clear communication.",
  "Slow down to gain control and accuracy.",
  "Your focus determines your typing success.",
  "Practice transforms frustration into fun.",
  "Typing is a skill shaped by deliberate effort.",
  "Every word typed builds your confidence.",
  "Discipline today brings ease tomorrow.",
  "The road to mastery is paved with patience.",
  "Celebrate progress, not perfection.",
  "You are stronger than your mistakes.",
  "Focus on progress, no matter how small.",
  "Typing is a skill that empowers your voice.",
  "Speed will come with confidence and care.",
  "Your dedication is your greatest asset.",
  "Practice regularly to make typing effortless.",
  "Typing is a bridge between ideas and reality.",
  "Every keystroke reflects your commitment.",
  "Slow and steady typing wins the race.",
  "The rhythm of your typing creates your success.",
  "Each word typed is a step forward.",
  "Typing mastery is earned one keystroke at a time.",
  "Let your fingers express your thoughts freely.",
  "Consistent practice is the key to fluency.",
  "Keep pushing; mastery is within your reach.",
  "Typing is a journey worth every moment.",
  "Accuracy is the heart of fast typing.",
  "Your focus shapes your typing progress.",
  "Practice daily to unlock your potential.",
  "Mistakes are lessons in disguise.",
  "Typing is an art refined by repetition.",
  "Confidence and patience breed typing success.",
  "Every session strengthens your skills.",
  "Typing is a conversation between mind and fingers.",
  "Be patient; greatness takes time.",
  "Your dedication sets you apart.",
  "Slow down to speed up.",
  "Typing is the language of the digital age.",
  "Progress happens one keystroke at a time.",
  "Celebrate every small victory.",
  "Your fingers are tools of creation.",
  "Keep your eyes on the goal.",
  "Typing skill grows with every practice.",
  "Never give up on your goals.",
  "Typing mastery is a marathon, not a sprint.",
  "The keyboard is your creative playground.",
  "Focus fuels progress.",
  "Mistakes mean you’re learning.",
  "Every practice session counts.",
  "Slow, steady typing leads to excellence.",
  "Typing is the art of turning thoughts into words.",
  "Patience is your greatest ally.",
  "Stay consistent and watch your skills grow.",
  "Your typing journey is unique and valuable.",
  "Typing fast requires calm and control.",
  "Celebrate the joy of progress.",
  "Typing is a skill for life.",
  "Every keystroke is a step forward.",
  "Typing opens doors to new opportunities.",
  "Mastery is built on patience and practice.",
  "Keep typing, keep improving.",
  "Your effort today shapes your tomorrow.",
  "Practice makes progress.",
  "Typing is an investment in yourself.",
  "Stay focused, stay determined.",
  "Your fingers hold the power to create.",
  "Typing is a craft worth perfecting.",
  "Each mistake is a lesson learned.",
  "Dedication brings success.",
  "Typing is a dance of mind and fingers.",
  "Celebrate your typing victories.",
  "Patience and persistence win the race.",
  "Typing well is a superpower.",
  "Every word you type builds confidence.",
  "Typing fast is a byproduct of accuracy.",
  "Your journey to mastery starts now.",
  "Stay motivated and keep practicing.",
  "Typing fluency requires daily effort.",
  "Keep calm and type on.",
  "The keyboard is your instrument of expression.",
  "Practice with passion and purpose.",
  "Typing connects you to the world.",
  "Celebrate each improvement, no matter how small.",
  "Typing mastery is within your reach.",
  "Focus on accuracy, and speed will follow.",
  "Every practice session is progress.",
  "Typing transforms ideas into reality.",
  "Patience turns effort into excellence.",
  "Your dedication makes the difference.",
  "Keep pushing through challenges.",
  "Typing is a skill that grows with practice.",
  "Celebrate the art of typing.",
  "Slow and steady builds typing strength.",
  "Every keystroke is progress.",
  "Typing well empowers communication.",
  "Stay dedicated, stay successful.",
  "Typing is the key to digital literacy.",
  "Your fingers are tools of creativity.",
  "Practice daily to build fluency.",
  "Typing is a skill that lasts a lifetime.",
  "Celebrate your typing journey.",
  "Patience and practice create mastery.",
  "Typing speed comes with confidence.",
  "Your focus shapes your progress.",
  "Keep typing and keep growing.",
  "Typing transforms thoughts into action.",
  "Stay motivated and never give up.",
  "Every word typed is a victory.",
  "Typing is a bridge between ideas and expression.",
  "Practice with purpose and passion.",
  "Typing mastery is earned one step at a time.",
  "Celebrate every moment of progress.",
  "Patience turns practice into skill.",
  "Your dedication fuels success.",
  "Keep going, no matter what.",
  "Typing is an art refined by effort.",
  "Every practice session strengthens skills.",
  "Typing well opens doors to opportunity.",
  "Stay focused and keep improving.",
  "Typing is a journey worth taking.",
  "Celebrate the joy of typing.",
  "Patience and persistence lead to mastery.",
  "Typing is a powerful tool for communication.",
  "Your fingers are your greatest asset.",
  "Practice regularly to build confidence.",
  "Typing mastery starts with a single keystroke.",
  "Keep pushing through challenges.",
  "Typing fast is a result of consistent effort.",
  "Celebrate progress over perfection.",
  "Patience and dedication create success.",
  "Typing is a skill that changes lives.",
  "Every keystroke brings you closer to fluency.",
  "Stay focused and motivated.",
  "Typing connects you to the digital world.",
  "Practice daily for lasting improvement.",
  "Typing is a craft worth mastering.",
  "Celebrate each step of your journey.",
  "Patience transforms effort into excellence.",
  "Your dedication makes the difference.",
  "Keep going and never give up.",
  "Typing is a journey, not a destination.",
  "Every practice session is a step forward.",
  "Typing well empowers your voice.",
  "Stay motivated and keep practicing.",
  "Typing is the language of the modern world.",
  "Celebrate your typing achievements.",
  "Patience and persistence pay off.",
  "Typing fast is a skill, typing well is an art.",
  "Your fingers tell the story of your dedication.",
  "Practice with passion and purpose.",
  "Typing connects your thoughts to the world.",
  "Celebrate every word you type.",
  "Patience leads to mastery.",
  "Keep pushingand stay consistent.",
  "Typing is a gift you give yourself.",
  "Every keystroke counts.",
  "Typing is the rhythm of your thoughts.",
];
